version: 0.2
env:
  variables:
    key: "aws"
    key: "serverless"
phases:
  install:
    commands:
      - echo install phase...started on `date`
      - npm install
  pre_build:
    commands:
      - echo pre_build phase...started on `date`
      - node_modules/jslint/bin/jslint.js js/*.js
  build:
    commands:
      - echo build phase...started on `date`
      - npm test
  post_build:
    commands:
      - echo post_build phase...started on `date`
artifacts:
  files:
    - css/*
    - js/*
    - spa.html
  discard-paths: no
